{
  "comments": [
    {
      "key": {
        "uuid": "f6aa7159_4165c508",
        "filename": "extras/rpm/vpp.spec",
        "patchSetId": 2
      },
      "lineNbr": 57,
      "author": {
        "id": 1496
      },
      "writtenOn": "2019-04-17T16:28:03Z",
      "side": 1,
      "message": "Are we abandoning fedora?",
      "range": {
        "startLine": 52,
        "startChar": 0,
        "endLine": 57,
        "endChar": 20
      },
      "revId": "37f436c982528198cd3f95bbd567d86294a6824b",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1be8b582_54b2a72a",
        "filename": "extras/rpm/vpp.spec",
        "patchSetId": 2
      },
      "lineNbr": 57,
      "author": {
        "id": 32
      },
      "writtenOn": "2019-04-17T17:53:46Z",
      "side": 1,
      "message": "This patch applies specifically to Centos. It doesn\u0027t address Fedora.",
      "parentUuid": "f6aa7159_4165c508",
      "range": {
        "startLine": 52,
        "startChar": 0,
        "endLine": 57,
        "endChar": 20
      },
      "revId": "37f436c982528198cd3f95bbd567d86294a6824b",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "e71621b4_463aecc1",
        "filename": "extras/rpm/vpp.spec",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 1496
      },
      "writtenOn": "2019-04-17T16:28:03Z",
      "side": 1,
      "message": "python-ply replaced with python36-ply",
      "range": {
        "startLine": 63,
        "startChar": 48,
        "endLine": 63,
        "endChar": 58
      },
      "revId": "37f436c982528198cd3f95bbd567d86294a6824b",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "b58da16a_6b77eaf9",
        "filename": "extras/rpm/vpp.spec",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 32
      },
      "writtenOn": "2019-04-17T17:53:46Z",
      "side": 1,
      "message": "I suppose you are right that there is no reason for python-ply anymore. However, it won\u0027t do any harm because it is in Centos base and the release manager wants to merge this  patch today.",
      "parentUuid": "e71621b4_463aecc1",
      "range": {
        "startLine": 63,
        "startChar": 48,
        "endLine": 63,
        "endChar": 58
      },
      "revId": "37f436c982528198cd3f95bbd567d86294a6824b",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    }
  ]
}